name: Deploy to Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Pages
      run: |
        git config --global user.name "nebulaliu"
        git config --global user.email "nebulaliu@tencent.com"
        git remote set-url origin git@github.com:liuxinyumocn/vuepress-test.git
        git checkout --orphan pages
        git add -f ./docs
        git commit -m "Deploy from GitHub Actions"
        git push -f origin pages
      env:
        GIT_SSH_KEY: ${{ secrets.DEPLOY_KEY }}
