name: Deploy to Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Deploy to Pages
      run: |        
        git config --global user.name "nebulaliu"
        git config --global user.email "nebulaliu@tencent.com"
        git remote set-url origin git@github.com:liuxinyumocn/vuepress-test.git
        git checkout --orphan pages
        git rm -rf .
        mkdir docs
        rsync -av --exclude='.git' ./docs/ ./docs/
        git add -f .
        git commit -m "Deploy from GitHub Actions"
        git push -f origin pages
      env:
        GIT_SSH_KEY: ${{ secrets.DEPLOY_KEY }}
